version: '3'

services:
  app:
#    build: artlov/docker-tig .
    image: "artlov/docker-telegraf-influxdb-grafana"
    ports:
      - "3003:3003"
      - "3004:8888"
      - "8086:8086"
      - "22022:22"
      - "8125:8125/udp"
    environment:
      - "TZ=Europe/Tallinn"
    volumes:
      - /volume1/docker/influxdb:/var/lib/influxdb
      - /volume1/docker/grafana:/var/lib/grafana
      - /volume1/docker/backups:/var/backups


#test:
#  override:
#    - docker run -d -p 3003:3003 -p 3004:8888 -p 8086:8086 -p 22022:22 -p 8125:8125/udp artlov/docker-telegraf-influxdb-grafana; sleep 15
#    - curl --retry 10 --retry-delay 5 -v http://localhost:3003
#    - curl --retry 10 --retry-delay 5 -v http://localhost:3004
#    - curl --retry 10 --retry-delay 5 -v http://localhost:8086


# docker-compose up
# docker-compose stop
# docker-compose down
